# Generated by Django 5.2.5 on 2025-10-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0003_alter_publicacion_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
