# Generated by Django 5.2.5 on 2025-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0006_alter_publicacion_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
