# Generated by Django 5.2.5 on 2025-10-28 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0008_remove_usuarios_modooscuro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='topico',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='topico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FPixAda.topicos'),
        ),
    ]
