# Generated by Django 5.2.5 on 2025-10-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0009_remove_publicacion_topico_publicacion_topico'),
        ('FPixAda', '0010_remove_perfilusuario_alias'),
    ]

    operations = [
    ]
