# Generated by Django 5.2.5 on 2025-10-30 13:31

import FPixAda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0012_alter_perfilusuario_fotoperfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='fuckIt/a.png'),
        ),
    ]
