# Generated by Django 5.2.5 on 2025-10-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0013_alter_perfilusuario_fotoperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fotoperfil',
        ),
    ]
