# Generated by Django 5.2.5 on 2025-11-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0014_remove_perfilusuario_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fotoPerfil',
            field=models.CharField(blank=True),
        ),
    ]
