# Generated by Django 5.2.5 on 2025-11-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0018_alter_usuarios_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='enRevision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='ofensivo',
            field=models.BooleanField(default=False),
        ),
    ]
