# Generated by Django 5.2.5 on 2025-10-12 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('aliasUsuario', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('adm', 'Administrador'), ('mod', 'Moderador'), ('usr', 'Usuario')], default='usr', max_length=15)),
                ('modoOscuro', models.BooleanField(default=False)),
                ('yanMode', models.BooleanField(default=False)),
                ('altoContraste', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idPublicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(auto_now_add=True, null=True)),
                ('cuerpo', models.TextField()),
                ('esAnonimo', models.BooleanField(default=False)),
                ('topico', models.ManyToManyField(blank=True, to='FPixAda.topicos')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FPixAda.usuarios')),
            ],
        ),
    ]
