# Generated by Django 5.2.5 on 2025-10-14 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='cuerpo',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='aliasUsuario',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.CharField(max_length=200)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FPixAda.usuarios')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FPixAda.publicacion')),
            ],
        ),
    ]
