# Generated by Django 5.2.5 on 2025-10-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0002_alter_publicacion_cuerpo_alter_usuarios_aliasusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fechaCreacion',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
