# Generated by Django 5.2.5 on 2025-10-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0005_usuarios_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fechaCreacion',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
