# Generated by Django 5.2.5 on 2025-10-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0007_alter_publicacion_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='modoOscuro',
        ),
    ]
