# Generated by Django 5.2.5 on 2025-10-29 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0008_remove_usuarios_modooscuro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='perfilusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=700)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
