# Generated by Django 5.2.5 on 2025-10-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0009_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='alias',
        ),
    ]
