# Generated by Django 5.2.5 on 2025-10-29 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0011_merge_20251029_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/usuario_<django.db.models.fields.related.OneToOneField>/perfil'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FPixAda.usuarios'),
        ),
    ]
