# Generated by Django 5.2.5 on 2025-11-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0015_perfilusuario_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='esAnonimo',
            field=models.BooleanField(default=False),
        ),
    ]
