# Generated by Django 5.2.5 on 2025-11-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0017_usuarios_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='creado',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
