# Generated by Django 5.2.5 on 2025-11-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0019_publicacion_enrevision_publicacion_ofensivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='motivoRevision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
