# Generated by Django 5.2.5 on 2025-11-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPixAda', '0020_publicacion_motivorevision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fotoPerfil',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
